<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 mac-draco.glb --shadows --transform
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { base } from '$app/paths';

	export const ref = new Group();

	const gltf = useGltf(base + '/models/mac-draco-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[0, -0.04, 0.41]} rotation={[0.01, 0, 0]}>
			<T.Group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube008.geometry}
					material={gltf.materials.aluminium}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube008_1.geometry}
					material={gltf.materials['matte.001']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube008_2.geometry}
					material={gltf.materials['screen.001']}
				>
					<slot name="screen" />
				</T.Mesh>
			</T.Group>
		</T.Group>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes.keyboard.geometry}
			material={gltf.materials.keys}
			position={[1.79, 0, 3.45]}
		/>
		<T.Group position={[0, -0.1, 3.39]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube002.geometry}
				material={gltf.materials.aluminium}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube002_1.geometry}
				material={gltf.materials.trackpad}
			/>
		</T.Group>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes.touchbar.geometry}
			material={gltf.materials.touchbar}
			position={[0, -0.03, 1.2]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
